// Client-safe file constants. Mirror of server-side limits in src/lib/storage.ts.
// Kept in a separate file so client components can import without pulling in
// the Prisma/megajs server-only modules.

export const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100 MB
export const MAX_FILE_SIZE_MB = 100;

export const MAX_ATTACHMENTS_PER_MESSAGE = 5;

// ─────────────────────────────────────────────────────────────────────────
// KEBIJAKAN BARU: SEMUA tipe file didukung (cloud & mount MEGA).
// Tidak ada lagi whitelist penolakan mimetype — dulu file .sh / .py / .cdr /
// .gdoc dsb. ditolak dengan "MIME_NOT_ALLOWED" karena mimetype OS kosong
// atau tidak masuk daftar. Sekarang:
//   1. Upload menerima apapun (batas tetap: ukuran & file kosong).
//   2. resolveMime hanya MENORMALISASI label (OS mime valid → ekstensi →
//      application/octet-stream), bukan menolak.
//   3. Keamanan tetap dijaga saat SERVING (lihat /api/storage/[key]):
//      magic-byte sniffing, X-Content-Type-Options: nosniff, CSP sandbox
//      untuk html/svg, disposition inline. Tipe tak dikenal diunduh sebagai
//      file — browser tidak pernah mengeksekusinya.
//   4. Pratinjau ditangani Aula Reader / pratinjau bawaan: CorelDraw (.cdr)
//      & RAW kamera ditampilkan sebagai gambar (thumbnail ter-embed),
//      file pintasan Google (.gdoc dst.) membuka Google Docs, dsb.
// ─────────────────────────────────────────────────────────────────────────

// Peta ekstensi → mimetype. Diperluas agar file dari "seluruh dunia" tetap
// terlabel benar (serving, ikon, dan klasifikasi pratinjau).
export const EXT_MIME: Record<string, string> = {
  // ── Dokumen & PDF ──
  pdf: "application/pdf",
  txt: "text/plain",
  text: "text/plain",
  log: "text/plain",
  ini: "text/plain",
  cfg: "text/plain",
  conf: "text/plain",
  env: "text/plain",
  properties: "text/plain",
  prop: "text/plain",
  md: "text/markdown",
  markdown: "text/markdown",
  mdx: "text/markdown",
  csv: "text/csv",
  tsv: "text/tab-separated-values",
  json: "application/json",
  jsonl: "application/json",
  ndjson: "application/json",
  geojson: "application/geo+json",
  ipynb: "application/x-ipynb+json",
  xml: "application/xml",
  xsl: "application/xml",
  plist: "application/xml",
  yaml: "text/yaml",
  yml: "text/yaml",
  toml: "text/plain",
  rtf: "application/rtf",
  epub: "application/epub+zip",
  mobi: "application/x-mobipocket-ebook",
  azw: "application/vnd.amazon.ebook",
  azw3: "application/vnd.amazon.ebook",
  djvu: "image/vnd.djvu",
  djv: "image/vnd.djvu",
  cbz: "application/vnd.comicbook+zip",
  cbr: "application/vnd.comicbook-rar",
  chm: "application/vnd.ms-htmlhelp",
  xps: "application/oxps",
  oxps: "application/oxps",
  wpd: "application/vnd.wordperfect",
  wps: "application/vnd.ms-works",
  wks: "application/vnd.ms-works",
  one: "application/onenote",
  msg: "application/vnd.ms-outlook",
  eml: "message/rfc822",
  ics: "text/calendar",
  ifb: "text/calendar",
  vcf: "text/vcard",
  vtt: "text/vtt",
  srt: "application/x-subrip",
  ass: "text/plain",
  ssa: "text/plain",
  lrc: "text/plain",

  // ── Pintasan Google Drive (file .gdoc dll adalah JSON kecil berisi URL) ──
  gdoc: "application/vnd.google-apps.document",
  gsheet: "application/vnd.google-apps.spreadsheet",
  gslides: "application/vnd.google-apps.presentation",
  gdraw: "application/vnd.google-apps.drawing",
  gform: "application/vnd.google-apps.form",
  gmap: "application/vnd.google-apps.map",
  gsite: "application/vnd.google-apps.site",
  gpres: "application/vnd.google-apps.presentation",
  gsheetx: "application/vnd.google-apps.spreadsheet",

  // ── Kode (pratinjau teks + syntax) ──
  html: "text/html",
  htm: "text/html",
  xhtml: "text/html",
  css: "text/css",
  scss: "text/x-scss",
  sass: "text/x-sass",
  less: "text/x-less",
  styl: "text/x-stylus",
  js: "text/javascript",
  mjs: "text/javascript",
  cjs: "text/javascript",
  ts: "text/x-typescript",
  mts: "text/x-typescript",
  cts: "text/x-typescript",
  tsx: "text/x-typescript",
  jsx: "text/javascript",
  vue: "text/x-vue",
  svelte: "text/x-svelte",
  astro: "text/x-astro",
  py: "text/x-python",
  pyw: "text/x-python",
  pyi: "text/x-python",
  rb: "text/x-ruby",
  php: "application/x-httpd-php",
  phtml: "application/x-httpd-php",
  java: "text/x-java-source",
  jar: "application/java-archive",
  war: "application/java-archive",
  c: "text/x-c",
  h: "text/x-c",
  cpp: "text/x-c++",
  cxx: "text/x-c++",
  cc: "text/x-c++",
  hpp: "text/x-c++",
  hh: "text/x-c++",
  cs: "text/x-csharp",
  fs: "text/x-fsharp",
  fsx: "text/x-fsharp",
  go: "text/x-go",
  rs: "text/x-rust",
  swift: "text/x-swift",
  kt: "text/x-kotlin",
  kts: "text/x-kotlin",
  scala: "text/x-scala",
  sc: "text/x-scala",
  lua: "text/x-lua",
  pl: "text/x-perl",
  pm: "text/x-perl",
  r: "text/x-r",
  jl: "text/x-julia",
  m: "text/x-objective-c",
  mm: "text/x-objective-c",
  dart: "text/x-dart",
  groovy: "text/x-groovy",
  gradle: "text/x-groovy",
  clj: "text/x-clojure",
  cljs: "text/x-clojure",
  cljc: "text/x-clojure",
  edn: "text/x-clojure",
  ml: "text/x-ocaml",
  mli: "text/x-ocaml",
  ex: "text/x-elixir",
  exs: "text/x-elixir",
  erl: "text/x-erlang",
  hrl: "text/x-erlang",
  hs: "text/x-haskell",
  lhs: "text/x-haskell",
  elm: "text/x-elm",
  nim: "text/x-nim",
  zig: "text/x-zig",
  v: "text/x-v",
  as: "text/x-actionscript",
  asm: "text/x-asm",
  s: "text/x-asm",
  f90: "text/x-fortran",
  f95: "text/x-fortran",
  for: "text/x-fortran",
  cob: "text/x-cobol",
  cbl: "text/x-cobol",
  pas: "text/x-pascal",
  pp: "text/x-pascal",
  dpr: "text/x-pascal",
  coffee: "text/x-coffeescript",
  tcl: "text/x-tcl",
  awk: "text/x-awk",
  sed: "text/x-sed",
  vim: "text/x-vim",
  nix: "text/x-nix",
  ps1: "text/x-powershell",
  psm1: "text/x-powershell",
  psd1: "text/x-powershell",
  bat: "text/plain",
  cmd: "text/plain",
  sh: "text/x-shellscript",
  bash: "text/x-shellscript",
  zsh: "text/x-shellscript",
  fish: "text/x-shellscript",
  sql: "application/sql",
  prisma: "text/plain",
  graphql: "application/graphql",
  gql: "application/graphql",
  proto: "text/x-protobuf",
  tf: "text/x-hcl",
  tfvars: "text/x-hcl",
  hcl: "text/x-hcl",
  dockerfile: "text/plain",
  makefile: "text/plain",
  mk: "text/plain",
  cmake: "text/plain",
  tex: "application/x-tex",
  sty: "application/x-tex",
  cls: "application/x-tex",
  bib: "application/x-bibtex",
  adoc: "text/x-asciidoc",
  asciidoc: "text/x-asciidoc",
  org: "text/x-org",
  rst: "text/x-rst",
  po: "text/x-gettext",
  pot: "text/x-gettext",
  mo: "application/x-gettext-binary",
  hbs: "text/x-handlebars",
  ejs: "text/x-ejs",
  pug: "text/x-pug",
  jade: "text/x-pug",
  twig: "text/x-twig",
  liquid: "text/x-liquid",
  jsp: "text/x-jsp",
  aspx: "text/x-aspx",
  ascx: "text/x-aspx",
  cshtml: "text/x-cshtml",
  razor: "text/x-cshtml",
  svg: "image/svg+xml",
  svgz: "image/svg+xml",

  // ── Gambar ──
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  jpe: "image/jpeg",
  jfif: "image/jpeg",
  pjpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  avif: "image/avif",
  avifs: "image/avif",
  jxl: "image/jxl",
  bmp: "image/bmp",
  dib: "image/bmp",
  ico: "image/x-icon",
  cur: "image/x-icon",
  ani: "image/x-icon",
  icns: "image/x-icns",
  tif: "image/tiff",
  tiff: "image/tiff",
  heic: "image/heic",
  heif: "image/heif",
  heifs: "image/heif",
  qoi: "image/qoi",
  tga: "image/x-tga",
  dds: "image/vnd.dds",
  exr: "image/x-exr",
  hdr: "image/vnd.radiance",
  pbm: "image/x-portable-bitmap",
  pgm: "image/x-portable-graymap",
  ppm: "image/x-portable-pixmap",
  pnm: "image/x-portable-anymap",

  // ── Gambar desain / proprietary (pratinjau via thumbnail ter-embed) ──
  cdr: "application/x-coreldraw",
  cpt: "application/x-corel-photo-paint",
  cdt: "application/x-coreldraw-template",
  cmx: "application/x-corel-metafile",
  pat: "application/x-corel-pattern",
  ai: "application/postscript",
  eps: "application/postscript",
  ps: "application/postscript",
  psd: "image/vnd.adobe.photoshop",
  psb: "image/vnd.adobe.photoshop",
  fig: "application/x-figma",
  sketch: "application/x-sketch",
  xd: "application/vnd.adobe.xd",
  afdesign: "application/x-affinity-designer",
  afphoto: "application/x-affinity-photo",
  afpub: "application/x-affinity-publisher",
  indd: "application/x-indesign",
  indt: "application/x-indesign",
  pmd: "application/x-pagemaker",
  pub: "application/x-mspublisher",
  vsd: "application/vnd.visio",
  vsdx: "application/vnd.visio",
  vsdm: "application/vnd.visio",
  drawio: "application/vnd.jgraph.mxfile",
  dio: "application/vnd.jgraph.mxfile",
  xcf: "image/x-xcf",
  kra: "application/x-krita",
  ora: "image/openraster",
  pxz: "application/x-pixlr",
  clip: "application/x-clipstudio",
  sai: "application/x-easytool",
  px: "application/x-pixlr",
  procreate: "application/x-procreate",
  gliffy: "application/json",
  kml: "application/vnd.google-earth.kml+xml",
  kmz: "application/vnd.google-earth.kmz",

  // ── RAW kamera (pratinjau via JPEG ter-embed) ──
  cr2: "image/x-canon-cr2",
  cr3: "image/x-canon-cr3",
  crw: "image/x-canon-crw",
  nef: "image/x-nikon-nef",
  nrw: "image/x-nikon-nrw",
  arw: "image/x-sony-arw",
  sr2: "image/x-sony-sr2",
  srf: "image/x-sony-srf",
  dng: "image/x-adobe-dng",
  orf: "image/x-olympus-orf",
  rw2: "image/x-panasonic-rw2",
  rwl: "image/x-panasonic-rwl",
  raf: "image/x-fuji-raf",
  pef: "image/x-pentax-pef",
  ptx: "image/x-pentax-ptx",
  srw: "image/x-samsung-srw",
  x3f: "image/x-sigma-x3f",
  erf: "image/x-epson-erf",
  iiq: "image/x-phaseone-iiq",
  kdc: "image/x-kodak-kdc",
  dcr: "image/x-kodak-dcr",
  mrw: "image/x-minolta-mrw",
  bay: "image/x-casio-bay",
  fff: "image/x-hasselblad-fff",
  mef: "image/x-mamiya-mef",
  mdc: "image/x-minolta-mdc",
  "3fr": "image/x-hasselblad-3fr",

  // ── Audio ──
  mp3: "audio/mpeg",
  mp2: "audio/mpeg",
  m4a: "audio/mp4",
  m4b: "audio/mp4",
  m4p: "audio/mp4",
  wav: "audio/wav",
  wave: "audio/wav",
  ogg: "audio/ogg",
  oga: "audio/ogg",
  opus: "audio/ogg",
  flac: "audio/flac",
  aac: "audio/aac",
  aif: "audio/aiff",
  aiff: "audio/aiff",
  aifc: "audio/aiff",
  wma: "audio/x-ms-wma",
  amr: "audio/amr",
  mid: "audio/midi",
  midi: "audio/midi",
  mod: "audio/x-mod",
  xm: "audio/x-xm",
  it: "audio/x-it",
  s3m: "audio/x-s3m",
  far: "audio/x-far",
  ape: "audio/ape",
  wv: "audio/wavpack",
  mka: "audio/x-matroska",
  caf: "audio/x-caf",
  weba: "audio/webm",
  dsf: "audio/x-dsf",
  dff: "audio/x-dff",
  mpc: "audio/x-musepack",
  m3u: "audio/x-mpegurl",
  m3u8: "application/vnd.apple.mpegurl",

  // ── Video ──
  mp4: "video/mp4",
  m4v: "video/mp4",
  webm: "video/webm",
  mov: "video/quicktime",
  qt: "video/quicktime",
  mkv: "video/x-matroska",
  avi: "video/x-msvideo",
  wmv: "video/x-ms-wmv",
  asf: "video/x-ms-asf",
  flv: "video/x-flv",
  f4v: "video/x-f4v",
  mpg: "video/mpeg",
  mpeg: "video/mpeg",
  mpe: "video/mpeg",
  m1v: "video/mpeg",
  m2v: "video/mpeg",
  m2ts: "video/mp2t",
  mts: "video/mp2t",
  ts: "video/mp2t",
  vob: "video/dvd",
  ogv: "video/ogg",
  divx: "video/x-divx",
  rm: "application/vnd.rn-realmedia",
  rmvb: "application/vnd.rn-realmedia-vbr",
  "3gp": "video/3gpp",
  "3g2": "video/3gpp2",
  mxf: "application/mxf",
  dv: "video/x-dv",
  swf: "application/x-shockwave-flash",
  fla: "application/x-adobe-fla",

  // ── Office ──
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  docm: "application/vnd.ms-word.document.macroEnabled.12",
  dot: "application/msword",
  dotx: "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xlsm: "application/vnd.ms-excel.sheet.macroEnabled.12",
  xlsb: "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
  xlt: "application/vnd.ms-excel",
  xla: "application/vnd.ms-excel",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  pptm: "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
  odt: "application/vnd.oasis.opendocument.text",
  ods: "application/vnd.oasis.opendocument.spreadsheet",
  odp: "application/vnd.oasis.opendocument.presentation",
  odg: "application/vnd.oasis.opendocument.graphics",
  odc: "application/vnd.oasis.opendocument.chart",
  odf: "application/vnd.oasis.opendocument.formula",
  odb: "application/vnd.oasis.opendocument.database",
  odi: "application/vnd.oasis.opendocument.image",
  pages: "application/x-iwork-pages-sffpages",
  numbers: "application/x-iwork-numbers-sffnumbers",
  key: "application/x-iwork-keynote-sffkey",
  mdb: "application/x-msaccess",
  accdb: "application/x-msaccess",
  dbf: "application/x-dbf",
  udl: "text/plain",

  // ── Arsip & kompresi ──
  zip: "application/zip",
  rar: "application/vnd.rar",
  "7z": "application/x-7z-compressed",
  tar: "application/x-tar",
  gz: "application/gzip",
  tgz: "application/gzip",
  bz2: "application/x-bzip2",
  xz: "application/x-xz",
  zst: "application/zstd",
  lz4: "application/x-lz4",
  lzma: "application/x-lzma",
  br: "application/x-brotli",
  cab: "application/vnd.ms-cab-compressed",
  arj: "application/x-arj",
  lzh: "application/x-lzh",
  iso: "application/x-iso9660-image",
  img: "application/octet-stream",
  dmg: "application/x-apple-diskimage",
  pkg: "application/x-newton-compatible-pkg",

  // ── Data & database ──
  db: "application/x-sqlite3",
  sqlite: "application/x-sqlite3",
  sqlite3: "application/x-sqlite3",
  db3: "application/x-sqlite3",
  bak: "application/octet-stream",
  dat: "application/octet-stream",
  parquet: "application/vnd.apache.parquet",
  arrow: "application/vnd.apache.arrow.file",
  hdf5: "application/x-hdf5",
  h5: "application/x-hdf5",
  npy: "application/octet-stream",
  npz: "application/octet-stream",
  pickle: "application/octet-stream",
  pkl: "application/octet-stream",

  // ── Executables / installer / library (diunduh, tidak dipratinjau) ──
  exe: "application/x-msdownload",
  msi: "application/x-msi",
  msix: "application/x-msi",
  appx: "application/x-msi",
  msp: "application/x-msi",
  apk: "application/vnd.android.package-archive",
  xapk: "application/vnd.android.package-archive",
  ipa: "application/octet-stream",
  deb: "application/vnd.debian.binary-package",
  rpm: "application/x-rpm",
  appimage: "application/x-executable",
  class: "application/java-vm",
  dll: "application/x-msdownload",
  so: "application/x-sharedlib",
  dylib: "application/x-sharedlib",
  bin: "application/octet-stream",
  run: "application/x-executable",
  shbundle: "application/x-executable",
  flatpak: "application/vnd.flatpak",
  snap: "application/vnd.snap",

  // ── Font ──
  ttf: "font/ttf",
  otf: "font/otf",
  ttc: "font/collection",
  woff: "font/woff",
  woff2: "font/woff2",
  eot: "application/vnd.ms-fontobject",
  pfb: "application/x-font-type1",
  pfm: "application/x-font-type1",

  // ── CAD / 3D ──
  dwg: "image/vnd.dwg",
  dxf: "image/vnd.dxf",
  stl: "model/stl",
  obj: "text/plain",
  gltf: "model/gltf+json",
  glb: "model/gltf-binary",
  fbx: "application/octet-stream",
  skp: "application/octet-stream",
  blend: "application/x-blender",
  dae: "model/vnd.collada+xml",
  step: "application/step",
  stp: "application/step",
  iges: "model/iges",
  igs: "model/iges",

  // ── Lainnya ──
  torrent: "application/x-bittorrent",
  url: "text/plain",
  lnk: "application/octet-stream",
  swp: "application/octet-stream",
  lock: "text/plain",
  sum: "text/plain",
  crt: "application/x-x509-ca-cert",
  pem: "application/x-pem-file",
  key: "application/octet-stream",
  p12: "application/x-pkcs12",
  pfx: "application/x-pkcs12",
};

const MIME_RE =
  /^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*(;.*)?$/;

/**
 * Mimetype final untuk sebuah file — SEMUA tipe diterima:
 * 1. mimetype OS dipakai kalau bentuknya valid (type/subtype),
 * 2. kalau kosong/aneh → infer dari ekstensi,
 * 3. sisanya → "application/octet-stream" (tetap lolos; tipe asli
 *    dideteksi server saat serving via magic bytes, dan pratinjau
 *    ditangani Aula Reader berdasarkan ekstensi).
 */
export function resolveMime(
  filename: string,
  osMime: string | null | undefined
): string {
  const m = (osMime || "").trim().toLowerCase();
  if (m && MIME_RE.test(m) && m !== "application/octet-stream") return m;
  const ext = filename.includes(".")
    ? filename.split(".").pop()!.toLowerCase()
    : "";
  const fromExt = ext ? EXT_MIME[ext] : undefined;
  if (fromExt) return fromExt;
  if (m) return m; // mimetype OS valid tapi ekstensi tak dikenal → pakai OS
  return "application/octet-stream";
}

export function isImageMime(mime: string): boolean {
  return mime.startsWith("image/");
}

/**
 * Mimetype dari ekstensi nama file saja (tanpa mimetype OS).
 * Kompatibilitas call-site lama; gunakan resolveMime bila mimetype OS
 * dari browser/OS tersedia.
 */
export function mimetypeFromName(name: string): string {
  return resolveMime(name, "");
}

export function formatBytes(n: number): string {
  if (!Number.isFinite(n) || n < 0) return "—";
  if (n === 0) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.min(units.length - 1, Math.floor(Math.log(n) / Math.log(1024)));
  const value = n / Math.pow(1024, i);
  const digits = i === 0 ? 0 : value < 10 ? 1 : 0;
  return `${value.toFixed(digits)} ${units[i]}`;
}

// Build the public URL that serves a stored file via the auth-gated
// /api/storage/[key] endpoint. Files are served as a stream — the route
// enforces canViewFile permission per request.
export function filePublicUrl(storageKey: string): string {
  return `/api/storage/${storageKey}`;
}
